formatVersion: 1
name: Application with Networking and Security
version: 1
inputs: {}
resources:
  sg-web:
    type: Cloud.SecurityGroup
    metadata:
      layoutPosition:
        - 0
        - 2
    properties:
      securityGroupType: new
      rules:
        - name: http
          direction: inbound
          protocol: TCP
          ports: 80
          source: any
  Cloud_NSX_LoadBalancer_1:
    type: Cloud.NSX.LoadBalancer
    metadata:
      layoutPosition:
        - 1
        - 1
    properties:
      routes:
        - protocol: HTTP
          port: 80
          instanceProtocol: HTTP
          instancePort: 80
          algorithm: IP_HASH
      network: '${resource.Cloud_vSphere_Network_1.id}'
      loggingLevel: NOTICE
      instances:
        - '${resource.frontend.id}'
  frontend:
    type: Cloud.Machine
    metadata:
      layoutPosition:
        - 1
        - 2
    properties:
      flavor: small
      image: Ubuntu18
      count: '1'
      constraints:
        - tag: 'cloud:vsphere'
      networks:
        - network: '${resource.Cloud_NSX_Network_1.id}'
          securityGroups:
            - '${resource["sg-web"].id}'
  Cloud_vSphere_Network_1:
    type: Cloud.vSphere.Network
    metadata:
      layoutPosition:
        - 2
        - 0
    properties:
      networkType: existing
  Cloud_NSX_Network_1:
    type: Cloud.NSX.Network
    metadata:
      layoutPosition:
        - 3
        - 0
    properties:
      networkType: outbound
  Jumpbox:
    type: Cloud.vSphere.Machine
    metadata:
      layoutPosition:
        - 4
        - 1
    properties:
      image: Ubuntu18
      cpuCount: 1
      totalMemoryMB: 1024
      networks:
        - network: '${resource.Cloud_NSX_Network_1.id}'
          securityGroups:
            - '${resource["sg-base"].id}'
  Cloud_NSX_Gateway_1:
    type: Cloud.NSX.Gateway
    metadata:
      layoutPosition:
        - 4
        - 2
    properties:
      networks:
        - '${resource.Cloud_NSX_Network_1.id}'
      natRules:
        - index: 1
          translatedInstance: '${resource.Jumpbox.networks[0].id}'
          sourceIPs: any
          sourcePorts: 3001
          protocol: TCP
          destinationPorts: 22
          translatedPorts: 22
          description: SSH
  sg-base:
    type: Cloud.SecurityGroup
    metadata:
      layoutPosition:
        - 5
        - 1
    properties:
      securityGroupType: new
      rules:
        - name: SSH
          direction: inbound
          ports: 22
          source: any
